#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn build:check
yarn workspace @resourvereign/client lint-staged
yarn workspace @resourvereign/server lint-staged
yarn workspace @resourvereign/common lint-staged